# Generated by Django 4.0.4 on 2022-05-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='item',
            name='Age',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='Dswd',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='Name',
            field=models.TextField(default=''),
        ),
    ]
