# Generated by Django 4.0.4 on 2022-05-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0003_member_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
