# Generated by Django 4.0.3 on 2022-05-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.TextField(default='')),
                ('Ssection', models.TextField(default='')),
                ('nAddress', models.TextField(default='')),
                ('nBreed', models.TextField(default='')),
                ('nDay', models.TextField(default='')),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Svsystem.list')),
            ],
        ),
    ]
