# Generated by Django 4.0.3 on 2022-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Svsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stundentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.TextField(default='')),
                ('Sid', models.TextField(default='')),
                ('Ssection', models.TextField(default='')),
                ('Sviolation', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
